### ISSUE TITLE
Добавить README.md

### ISSUE THREAD

**Issue by olegpolyakov** [Shtyrman/dom#1]
В этом файле добавь название проекта и короткое описание.

**Comment by Shtyrman** [comment]
добавил файл

**Comment by olegpolyakov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Выполнить ДЗ №1](https://trello.com/c/iqNQpMJx/2-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D1%8C-%D0%B4%D0%B7-%E2%84%961)
